global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'memesnipe-v25'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Rule files
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Executor metrics
  - job_name: 'executor'
    static_configs:
      - targets: ['executor:9184']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Market data gateway metrics
  - job_name: 'market_data_gateway'
    static_configs:
      - targets: ['market_data_gateway:9185']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s

  # Portfolio manager metrics
  - job_name: 'portfolio_manager'
    static_configs:
      - targets: ['portfolio_manager:9100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Signer metrics
  - job_name: 'signer'
    static_configs:
      - targets: ['signer:8989']
    metrics_path: /metrics
    scrape_interval: 60s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
