pub mod config;
pub mod event_loop;
pub mod circuit_breaker;
pub mod strategy_registry;
pub mod strategies;
pub mod metrics;
pub mod signer_client;
pub mod health;
pub mod data_validation;
pub mod mev_protection;
pub mod risk_manager;
pub mod jupiter;
pub mod jito_client;
pub mod portfolio_allocator;
pub mod correlation_manager;
pub mod performance_attributor;
pub mod transaction_cost_analyzer;
pub mod execution_timer;
pub mod risk_overlay;
pub mod pnl_tracker;
pub mod strategy_evolution;
pub mod performance_dashboard;
pub mod advanced_circuit_breakers;
pub mod websocket_api;
pub mod production_config;

pub use config::Config;
pub use event_loop::EventLoop;
pub use circuit_breaker::CircuitBreaker;
pub use strategy_registry::{StrategyRegistry, initialize_strategies};
pub use metrics::Metrics;
pub use health::HealthChecker;
pub use data_validation::DataFreshnessValidator;
pub use mev_protection::{JitoClient, MevProtectionManager, MevProtectionLevel};
pub use portfolio_allocator::PortfolioAllocator;
pub use correlation_manager::CorrelationManager;
pub use transaction_cost_analyzer::TransactionCostAnalyzer;
pub use execution_timer::ExecutionTimer;
